# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecord.proto\"\xff\x01\n\x06Record\x12\x11\n\trecord_id\x18\x01 \x01(\t\x12\x0e\n\x06tag_id\x18\x02 \x01(\t\x12\x1d\n\x06owners\x18\x03 \x03(\x0b\x32\r.Record.Owner\x12\"\n\thistories\x18\x04 \x03(\x0b\x32\x0f.Record.History\x1a,\n\x05Owner\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x1a\x61\n\x07History\x12\x11\n\treader_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nt_id\x18\x02 \x01(\t\x12\x11\n\tsituation\x18\x03 \x01(\x12\x12\r\n\x05token\x18\x04 \x01(\x12\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\"+\n\x0fRecordContainer\x12\x18\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x07.Recordb\x06proto3')



_RECORD = DESCRIPTOR.message_types_by_name['Record']
_RECORD_OWNER = _RECORD.nested_types_by_name['Owner']
_RECORD_HISTORY = _RECORD.nested_types_by_name['History']
_RECORDCONTAINER = DESCRIPTOR.message_types_by_name['RecordContainer']
Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), {

  'Owner' : _reflection.GeneratedProtocolMessageType('Owner', (_message.Message,), {
    'DESCRIPTOR' : _RECORD_OWNER,
    '__module__' : 'record_pb2'
    # @@protoc_insertion_point(class_scope:Record.Owner)
    })
  ,

  'History' : _reflection.GeneratedProtocolMessageType('History', (_message.Message,), {
    'DESCRIPTOR' : _RECORD_HISTORY,
    '__module__' : 'record_pb2'
    # @@protoc_insertion_point(class_scope:Record.History)
    })
  ,
  'DESCRIPTOR' : _RECORD,
  '__module__' : 'record_pb2'
  # @@protoc_insertion_point(class_scope:Record)
  })
_sym_db.RegisterMessage(Record)
_sym_db.RegisterMessage(Record.Owner)
_sym_db.RegisterMessage(Record.History)

RecordContainer = _reflection.GeneratedProtocolMessageType('RecordContainer', (_message.Message,), {
  'DESCRIPTOR' : _RECORDCONTAINER,
  '__module__' : 'record_pb2'
  # @@protoc_insertion_point(class_scope:RecordContainer)
  })
_sym_db.RegisterMessage(RecordContainer)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECORD._serialized_start=17
  _RECORD._serialized_end=272
  _RECORD_OWNER._serialized_start=129
  _RECORD_OWNER._serialized_end=173
  _RECORD_HISTORY._serialized_start=175
  _RECORD_HISTORY._serialized_end=272
  _RECORDCONTAINER._serialized_start=274
  _RECORDCONTAINER._serialized_end=317
# @@protoc_insertion_point(module_scope)
